spring:
  application:
    name: client-crud
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
          sql:
          BasicBinder: TRACE
server:
  port: 8081
  servlet:
    context-path: /client-crud