spring:
  application:
    name: client-crud
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    password: ftoapanta
    url: jdbc:postgresql://localhost:5432/pichincha
    username: pichincha

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
          sql:
          BasicBinder: TRACE
server:
  port: 8081
  servlet:
    context-path: /client-crud