version: '3.8'
services:
    db:
      image: postgres:16.1
      container_name: db-pichincha
      restart: always
      volumes:
        - ./sql/create_schema_bp.sql:/docker-entrypoint-initdb.d/create_schema.sql
        - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
      environment:
        POSTGRES_DB: 'pichincha'
        POSTGRES_USER: 'pichincha'
        POSTGRES_PASSWORD: 'ftoapanta'
      ports:
        - '5432:5432'